server:
  port: 17000

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/mini-test?useSSL=false&autoReconnect=true&autoReconnection=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Seoul
    username: root
    password:
    sql-script-encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

social:
  client:
    kakao:
      rest-api-key:
      secret-key:
      redirect-uri: http://127.0.0.1:8080/kakao-login
      grant_type: authorization_code

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
