spring:
  profiles:
    active: local
  datasource:
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/mini-test?useSSL=false&autoReconnect=true&autoReconnection=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Seoul
    username: root
    password:
    sql-script-encoding: UTF-8
  jpa:
    #    show-sql: true
    #    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
